SUPPORTED_ROOMS = [
    "PokerStars",
    "PokerStars.es",
    "PokerStars.it",
    "PokerStars.pt",
    "PokerStars.br",
    "GGPoker",
    "888poker",
    "Partypoker",
    "Winamax",
    "iPoker",
    "WPN (Americas Cardroom)",
    "PokerKing",
    "BlackChipPoker",
    "YaPoker",
    "Bet365",
    "Betfair",
    "Ladbrokes",
    "Coral",
    "William Hill",
    "RedStar",
    "CoinPoker",
    "Chico Poker Network",
    "Ignition",
    "Bovada",
]
