SUPPORTED_ROOMS = [
    "PokerStars",
    "PokerStars.be",
    "PokerStars.bg",
    "PokerStars.com",
    "PokerStars.desh",
    "PokerStars.de",
    "PokerStars.dk",
    "PokerStars.ee",
    "PokerStars.es",
    "PokerStars.eu",
    "PokerStars.fr",
    "PokerStars.gr",
    "PokerStars.it",
    "PokerStars.mi",
    "PokerStars.nj",
    "PokerStars.pa",
    "PokerStars.pt",
    "PokerStars.ro",
    "PokerStars.RuSo",
    "PokerStars.se",
    "PokerStars.uk",
    "Full Tilt",
    "Winamax Poker",
    "888 Poker",
    "888poker",
    "888poker.es",
    "888poker.dk",
    "888poker.it",
    "888poker.ro",
    "888poker.se",
    "888poker.pt",
    "888poker.de",
    "CarbonPoker",
    "Players Only",
    "Sportsbook Poker",
    "Odds Poker",
    "PartyPoker",
    "BetMGM(MI)",
    "BetMGM(PA)",
    "PartyPoker(NJ)",
    "partypoker.fr",
    "partypoker.es",
    "PMU",
    "Juicy Stakes",
    "Intertops Poker",
    "iPoker",
    "1Unibet Poker",
    "Admiral Poker",
    "bet365 Poker",
    "bet365",
    "bet365.ee",
    "bet365.es",
    "bet365.it",
    "Bet365.nl Poker",
    "bet-at-home.com",
    "Bet-at-home.com",
    "Betclic Poker",
    "Betclic Poker.fr",
    "Betclic Poker.it",
    "Betclic",
    "Betclic.fr",
    "Betfair Poker",
    "Betfair.dk Poker",
    "Betfair.es Poker",
    "Betfair.it Poker",
    "Betfred Poker",
    "Bets10.com Poker",
    "Betsafe Poker",
    "Betsson Poker",
    "Betsson",
    "Bgame Poker",
    "Boyles Poker",
    "Casino Barcelona Poker",
    "Championpoker",
    "Coolbet Poker",
    "Coral Poker",
    "Dafabet Poker",
    "En ligne",
    "Eurobet Poker",
    "Expekt Poker",
    "Grosvenor Poker",
    "Holland Casino",
    "Ladbrokes Poker",
    "Lottomatica.it",
    "NetBet Poker",
    "Netbet.ro",
    "NordicBet",
    "Nordicbet.dk Poker",
    "Nordicbet.fi Poker",
    "Nordicbet.se Poker",
    "Paddy Power Poker",
    "Paf Poker",
    "Poker at Bet365",
    "Poker at Bet365.BG",
    "Poker at Bet365.ES",
    "Poker at Sports Interaction",
    "Poker Bets10",
    "Poker Guts",
    "Poker Snai",
    "Poker Swiss Casinos",
    "PokerMatch",
    "PokerPlex Poker",
    "PokerPlex24.it",
    "Red Star Poker",
    "Redstar Poker",
    "Sisal Poker",
    "Snai Poker",
    "Sportium Poker",
    "Svenska Spel Poker",
    "Swiss Casinos Poker",
    "Titan Poker",
    "Titanbet Poker UK",
    "Titanbet.it",
    "William Hill Poker",
    "William Hill.it",
    "win2day Poker",
    "Winner Poker",
    "Winning Poker Network",
    "America's Cardroom",
    "BlackChipPoker",
    "True Poker",
    "PokerKing",
    "YaPoker",
    "PokerNuts",
    "Poker4You",
    "FabulousPoker",
    "GGPoker",
    "CoinPoker",
    "Chico Poker Network",
    "Ignition",
    "Bovada",
]


def _normalize_room_key(value: str) -> str:
    cleaned = " ".join((value or "").strip().casefold().split())
    return "".join(char for char in cleaned if char.isalnum())


_EXACT_ROOM_MAP = {room.strip().casefold(): room for room in SUPPORTED_ROOMS}
_NORMALIZED_ROOM_MAP: dict[str, str] = {}
for _room in SUPPORTED_ROOMS:
    _key = _normalize_room_key(_room)
    _NORMALIZED_ROOM_MAP.setdefault(_key, _room)

_ROOM_ALIASES = {
    "gg": "GGPoker",
    "ggpoker": "GGPoker",
    "ggnetwork": "GGPoker",
    "888": "888poker",
    "888poker": "888poker",
    "partypoker": "PartyPoker",
    "party": "PartyPoker",
    "pokerstars": "PokerStars",
    "pokerstarscom": "PokerStars.com",
    "pokerstarses": "PokerStars.es",
    "pokerstarsit": "PokerStars.it",
    "pokerstarspt": "PokerStars.pt",
    "pokerstarsruso": "PokerStars.RuSo",
    "fulltilt": "Full Tilt",
    "winamax": "Winamax Poker",
    "888pokeres": "888poker.es",
    "888pokerit": "888poker.it",
    "888pokerpt": "888poker.pt",
    "ipoker": "iPoker",
    "acr": "America's Cardroom",
    "americascardroom": "America's Cardroom",
    "winningpokernetwork": "Winning Poker Network",
    "wpn": "Winning Poker Network",
    "chico": "Chico Poker Network",
    "redstar": "Red Star Poker",
    "williamhill": "William Hill Poker",
    "ladbrokes": "Ladbrokes Poker",
    "bet365nl": "Bet365.nl Poker",
}


def normalize_supported_room(room: str) -> str | None:
    if not room:
        return None
    compact = room.strip()
    if not compact:
        return None

    exact = _EXACT_ROOM_MAP.get(compact.casefold())
    if exact:
        return exact

    normalized_key = _normalize_room_key(compact)
    if not normalized_key:
        return None

    aliased = _ROOM_ALIASES.get(normalized_key)
    if aliased:
        return aliased
    return _NORMALIZED_ROOM_MAP.get(normalized_key)
